
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 23 03:16:40 CST 2015
//----------------------------------------------------

package servicio1deco;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 40;
  public static final int DOSPUNTOS = 6;
  public static final int FUNCTION = 7;
  public static final int POR = 44;
  public static final int XOR = 56;
  public static final int CASE = 26;
  public static final int PC = 13;
  public static final int CONTINUE = 21;
  public static final int REPEAT = 29;
  public static final int PA = 12;
  public static final int PUNTOCOMA = 5;
  public static final int TFALSE = 47;
  public static final int tbool = 18;
  public static final int NOT = 57;
  public static final int AND = 54;
  public static final int MENORIGUAL = 53;
  public static final int IGUAL = 58;
  public static final int ELSEIF = 25;
  public static final int tint = 14;
  public static final int OR = 55;
  public static final int DIV = 45;
  public static final int BEGIN = 37;
  public static final int UNTIL = 30;
  public static final int SELECT = 59;
  public static final int LOOP = 31;
  public static final int IF = 22;
  public static final int TMAIN = 4;
  public static final int COAB = 8;
  public static final int ID = 41;
  public static final int MAYORIGUAL = 51;
  public static final int OF = 32;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int TTRUE = 46;
  public static final int error = 1;
  public static final int PROGRAM = 33;
  public static final int COMA = 2;
  public static final int tstring = 15;
  public static final int DIF = 49;
  public static final int MENOS = 43;
  public static final int MENOR = 52;
  public static final int BREAK = 20;
  public static final int DOSIGUAL = 39;
  public static final int MAYOR = 50;
  public static final int LLC = 11;
  public static final int LLA = 10;
  public static final int ELSE = 24;
  public static final int COCI = 9;
  public static final int PUNTO = 3;
  public static final int IGUALIGUAL = 48;
  public static final int WHILE = 27;
  public static final int THEN = 23;
  public static final int END = 38;
  public static final int USES = 36;
  public static final int tdouble = 17;
  public static final int VAR = 35;
  public static final int PROCEDURE = 34;
  public static final int DO = 28;
  public static final int MAS = 42;
  public static final int tchar = 16;
}

